# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-03 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('db_fss', '0002_auto_20160327_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='matiere',
        ),
        migrations.AddField(
            model_name='student',
            name='matiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db_fss.Matiere'), preserve_default=False,),
    ]
