# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_fss', '0003_auto_20160306_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='chef_dep',
        ),
        migrations.AddField(
            model_name='departement',
            name='chefdep',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db_fss.Prof'),
            preserve_default=False,
        ),
    ]
