# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_fss', '0006_auto_20160306_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='n_url',
        ),
        migrations.AddField(
            model_name='news',
            name='contenu',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_fss.Prof'),
        ),
    ]
